### ISSUE TITLE
Varnish plugin incompatibility 

### ISSUE THREAD

**Issue by andre** [scoutapp/scout-plugins#209]
Customers using Varnish version 4 have reported a different output from `varnishstat`: a prefix in front of the stats name. For example, MAIN on these lines:

    MAIN.cache_hit                   744         0.04 Cache hits
    MAIN.cache_hitpass                30         0.00 Cache hits for pass
    MAIN.cache_miss                 4029         0.20 Cache misses

[This modified plugin code](https://gist.githubusercontent.com/andre/425b6a417e1ccaea4485/raw/7e979d0a9dcafa1f38489ddcc29065aa176a1fda/77483771.rb) fixed the problem by modifying the regex to: `/^[A-Z]+\.(\w+)\s+(\d+)\s+(\d+\.\d+)\s(.+)$/` (`[A-Z]+\.` in the regex is new)

Possible approach to fix: try the first regex, then fail over to the 2nd regex if the first fails.

**Comment by composit** [comment]
Fixed by allowing periods in the stat name: https://github.com/scoutapp/scout-plugins/commit/31bcb44539e1e8d2d36b68ba9461c891e3216ceb

Varnish 4 users will need to specify the namespace of the metrics monitored. It would be useful to change the default metric names for Varnish 4 as well, but this would break backwards compatibility.
